ALTER TABLE "Enrollment" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMPTZ DEFAULT NOW() NOT NULL;
ALTER TABLE "Enrollment" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMPTZ;
UPDATE "Enrollment" SET "updatedAt" = NOW() WHERE "updatedAt" IS NULL;
ALTER TABLE "Enrollment" ALTER COLUMN "updatedAt" SET NOT NULL;
ALTER TABLE "Enrollment" ALTER COLUMN "updatedAt" SET DEFAULT NOW();
