ALTER TABLE "Note" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMPTZ;
UPDATE "Note" SET "updatedAt" = NOW() WHERE "updatedAt" IS NULL;
ALTER TABLE "Note" ALTER COLUMN "updatedAt" SET NOT NULL;
ALTER TABLE "Note" ALTER COLUMN "updatedAt" SET DEFAULT NOW();
